uint8 STOP = 0
uint8 HOME = 1
uint8 MOVE_POSITION = 2
uint8 MOVE_VELOCITY = 3
uint8 command

int32 timeout 5 # default time to time out on a move position command

int32[] action
---
uint8 OK = 0
uint8 ERROR = 1
uint8 status

int32[] positions
int32[] velocities
int32[] loads

int32[] object_pose
---
uint8 status

int32[] positions
int32[] velocities
int32[] loads

int32[] object_pose